### ISSUE TITLE
为什么CINATRA_SINGLE_THREAD没定义的时候，num_threads = 1?

### ISSUE THREAD

**Issue by alvas** [topcpporg/cinatra#10]
#ifndef CINATRA_SINGLE_THREAD
		int num_threads_ = 1;
#else
		int num_threads_ = std::thread::hardware_concurrency();
#endif // CINATRA_SINGLE_THREAD

不知道是否我理解错误了，如果CINATRA_SINGLE_THREAD没定义，不是应该是多线程吗？为什么这里却说#ifndef CINATRA_SINGLE_THREAD, num_threads = 1?

**Comment by avdbg** [comment]
是的，这里是写反了，已修复
