### ISSUE TITLE
Compile error on Mac OSX

### ISSUE THREAD

**Issue by micfan** [topcpporg/cinatra#13]
Any help?
``` bash
[ 96%] Built target cinatra_test
2 warnings generated.
[100%] Linking CXX executable cinatra
cd /Users/mic/vm/ui/cinatra/build/examples/cinatra && /usr/local/Cellar/cmake/3.3.0/bin/cmake -E cmake_link_script CMakeFiles/cinatra.dir/link.txt --verbose=1
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++    -Wl,-search_paths_first -Wl,-headerpad_max_install_names  CMakeFiles/cinatra.dir/main.cpp.o  -o cinatra  /usr/local/lib/libboost_coroutine-mt.dylib /usr/local/lib/libboost_context-mt.dylib /usr/local/lib/libboost_system-mt.dylib /usr/local/lib/libboost_thread-mt.dylib /usr/local/lib/libboost_chrono-mt.dylib /usr/local/lib/libboost_date_time-mt.dylib /usr/local/lib/libboost_regex-mt.dylib /usr/local/lib/libboost_filesystem-mt.dylib /usr/local/lib/libboost_unit_test_framework-mt.dylib /usr/lib/libssl.dylib /usr/lib/libcrypto.dylib -lpthread 
Undefined symbols for architecture x86_64:
  "_ERR_remove_thread_state", referenced from:
      boost::asio::ssl::detail::openssl_init_base::do_init::~do_init() in main.cpp.o
  "_TLSv1_1_client_method", referenced from:
      boost::asio::ssl::context::context(boost::asio::ssl::context_base::method) in main.cpp.o
  "_TLSv1_1_method", referenced from:
      boost::asio::ssl::context::context(boost::asio::ssl::context_base::method) in main.cpp.o
  "_TLSv1_1_server_method", referenced from:
      boost::asio::ssl::context::context(boost::asio::ssl::context_base::method) in main.cpp.o
  "_TLSv1_2_client_method", referenced from:
      boost::asio::ssl::context::context(boost::asio::ssl::context_base::method) in main.cpp.o
  "_TLSv1_2_method", referenced from:
      boost::asio::ssl::context::context(boost::asio::ssl::context_base::method) in main.cpp.o
  "_TLSv1_2_server_method", referenced from:
      boost::asio::ssl::context::context(boost::asio::ssl::context_base::method) in main.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [examples/cinatra/cinatra] Error 1
make[1]: *** [examples/cinatra/CMakeFiles/cinatra.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by 123marvin123** [comment]
You need to have openssl installed. I recommend installing it via home-brew:

brew install openssl

**Comment by micfan** [comment]
@123marvin123 I have installed openssl 1.0, and cmake found it. This message is a link stage error, what does the `ld: symbol(s) not found for architecture x86_64` mean? Or, I can set `ENABLE_OPENSSL` to OFF

**Comment by lucklove** [comment]
If you don't need ssl, you can set ENABLE_OPENSSL to OFF.
We will test it on mac os for this problem.

**Comment by kirisetsz** [comment]
@micfan cmake tries to link with only `-lssl -lcrypto` option without `-L/usr/local/Cellar/openssl/1.0.2g/lib` which means that OS X's libssl implementation is used. Here is a [workaround](https://gist.github.com/kirisetsz/b3e575516cc0d743f705187d3f562152#file-nghttp2config-cmake-L7) by add a full path of ssl library file to linking configurations.

**Comment by micfan** [comment]
@kirisetsz 
Thank you. OpenSSL is a shit! If the maintainer wanna support Mac OSX, it's better to add a formula to HomeBrew. I have not tried your method... And it's a good idea distribute it to target OS, such as Ubuntu, Pacman, etc.

**Comment by kirisetsz** [comment]
It comes that I couldn't start a HTTP 1.1 service using nghttp2_asio :hankey: rewriting my program with cinatra now... :laughing:.
It's actually not an issue of OpenSSL but OS X. Maybe I can contribute the script as a part of OpenSSL CMake module, even though it's somewhat an ugly hack?

**Comment by lucklove** [comment]
@kirisetsz Welcome to contribute any work code.

**Comment by bouviervj** [comment]
I had the same issue on another Mac OS X project, I had to change also after the openssl installation with homebrew, links on libraries in /usr/lib , and also removing tbd files from MacOSX SDKs. Those tbd files contains a description of previous ssl lib methods and make fail the compilation at linking. This is a real issue for MacOSX that doesn't distribute the last version of openssl.
