### ISSUE TITLE
Use of angle brackets around file names for include statements

### ISSUE THREAD

**Issue by elfring** [topcpporg/cinatra#2]
Would you like to [replace any double quotes](https://github.com/topcpporg/cinatra/blob/04993745b9e7373f32bda8efbc9a61495fb5fc32/include/cinatra/cinatra.hpp#L4 "Check header file inclusion style") by [angle brackets around file names for include statements](http://stackoverflow.com/questions/21593/what-is-the-difference-between-include-filename-and-include-filename "What is the difference between #include <filename> and #include “filename”?")?

**Comment by lucklove** [comment]
Thanks for your issue, you are right, angle bracket is better than quote, so we take your advice:blush:

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/topcpporg/cinatra/commit/445d73673ae96639681f54c229eb866795f174d4 "Change for the header file inclusion style").
