### ISSUE TITLE
Translations of the wiki to English would be awesome!

### ISSUE THREAD

**Issue by thomasbrueggemann** [topcpporg/cinatra#3]

**Comment by qicosmos** [comment]
hi, thanks for your suggestion, we will translate it to english soon.

**Comment by qicosmos** [comment]
hi, thomasbrueggemann, we have already added english wiki here:https://github.com/topcpporg/cinatra/wiki/Introduction

**Comment by thomasbrueggemann** [comment]
Awesome!
