### ISSUE TITLE
issue in cinatra.hpp

### ISSUE THREAD

**Issue by ranky2009** [topcpporg/cinatra#5]
There was an issue in cinatra.hpp
void run()
{
    HTTPServer s(num_threads_);
    ....
    ...
}

need fixed as below:
void run()
{
#ifndef CINATRA_SINGLE_THREAD
    HTTPServer s(num_threads_);
#else
    HTTPServer s;
#endif
         ....
}

**Comment by avdbg** [comment]
Fixed.Thanks a lot.
