### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by phonzia** [topcpporg/cinatra#8]
compile error on g++ (Ubuntu 5.1.0-0ubuntu11~14.04.1) 5.1.0
cd /home/phonzia/cinatra/build/examples/cinatra && g++    -I/home/phonzia/cinatra/examples/cinatra/../../include    -std=c++1y -Wall -Wextra -o CMakeFiles/cinatra.dir/main.cpp.o -c /home/phonzia/cinatra/examples/cinatra/main.cpp
In file included from /home/phonzia/cinatra/examples/hello_world/main.cpp:1:0:
/home/phonzia/cinatra/examples/hello_world/../../include/cinatra/cinatra.hpp: In member function ‘T& cinatra::Cinatra<Aspect>::get_middleware()’:
/home/phonzia/cinatra/examples/hello_world/../../include/cinatra/cinatra.hpp:107:28: error: expected primary-expression before ‘>’ token
    return aop_.get_aspect<T>();
                            ^
/home/phonzia/cinatra/examples/hello_world/../../include/cinatra/cinatra.hpp:107:30: error: expected primary-expression before ‘)’ token
    return aop_.get_aspect<T>();
                              ^
In file included from /home/phonzia/cinatra/examples/cinatra/main.cpp:8:0:
/home/phonzia/cinatra/examples/cinatra/../../include/cinatra/cinatra.hpp: In member function ‘T& cinatra::Cinatra<Aspect>::get_middleware()’:
/home/phonzia/cinatra/examples/cinatra/../../include/cinatra/cinatra.hpp:107:28: error: expected primary-expression before ‘>’ token
    return aop_.get_aspect<T>();
                            ^
/home/phonzia/cinatra/examples/cinatra/../../include/cinatra/cinatra.hpp:107:30: error: expected primary-expression before ‘)’ token
    return aop_.get_aspect<T>();

**Comment by 123marvin123** [comment]
Change line 107 in cinatra.htpp to:
```c++
return aop_.template get_aspect<T>();
```

**Comment by lucklove** [comment]
Thank you for finger out that.
