### ISSUE TITLE
Chinese commit messages

### ISSUE THREAD

**Issue by 123marvin123** [topcpporg/cinatra#9]
Hey,

it would be nice if you guys could do english commit messages instead of chinese, because I cannot understand them.

(English comments in source code would be nice too.)

**Comment by avdbg** [comment]
This may be easier for @qicosmos  and @lucklove , but my English is very poor……
If I use English to write comment, I can only aid google translation.

**Comment by fawdlstty** [comment]
123marvin123是歪果仁？给你指条明路：学中文
